### ISSUE TITLE
[Bug] AccountType enumerator does not allow for a value of "enterprise"

### ISSUE THREAD

**Issue by jasonmwebb-lv** [zingz0r/CloudFlare.Client#58]
**Bug Description**
PersistenceUnavailableException is thrown when an enterprise account is being used. The AccountType enumerator does not allow for a value of "enterprise". As a result, the deserialization is failing for AccountType object when calling the "Accounts.GetDetailsAsync" method on an enterprise account. 

**Versions**
- CloudfFare.Client NuGet version 6.1.1
- Target framework: .NET 6.0

**To Reproduce**
1. Create CloudFlareClient with 'user email', and 'apiKey' authentication
2. Call 'Accounts.GetDetailsAsync' method on enterprise account
4. See the error
Error in Migrating list of domains: CloudFlare.Client.Exceptions.PersistenceUnavailableException: Exception occurred.
       ---> Newtonsoft.Json.JsonSerializationException: Error converting value "enterprise" to type 'CloudFlare.Client.Enumerators.AccountType'. Path 'result.type', line 1, position 107.
       ---> System.ArgumentException: Requested value 'enterprise' was not found.
         at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(Type enumType, NamingStrategy namingStrategy, String value, Boolean disallowNumber)
         at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
         --- End of inner exception stack trace ---
         at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
         at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
         at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
         at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
         at CloudFlare.Client.Extensions.HttpResponseMessageExtensions.GetCloudFlareResultAsync[T](HttpResponseMessage response)

**Expected behavior**
Deserialization should allow AccountType value of 'enterprise' in addition to 'standard'

**Comment by zingz0r** [comment]
Linking PR: #59

**Comment by zingz0r** [comment]
It will be in the next release (6.1.2)
